---

# Get latest Jenkins update file
- name: Get Jenkins updates
  sudo: yes
  get_url: url=http://updates.jenkins-ci.org/update-center.json
    dest={{jenkins['updates_dest']}}
    thirsty=yes
    mode=0440
  register: _jenkins_updates
  tags: ['jenkins', 'jenkins_plugins']

# Jenkins Update-center
- name: Update-center Jenkins
  sudo: yes
  shell: "cat {{jenkins['updates_dest']}} | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:{{jenkins['port']}}/updateCenter/byId/default/postBack"
  when: _jenkins_updates.changed
  tags: ['jenkins', 'jenkins_plugins']

- name: Install plugins
  sudo: yes
  command: java -jar {{ jenkins['cli_dest'] }} -s http://localhost:{{ jenkins['port'] }} install-plugin http://updates.jenkins-ci.org/download/plugins/{{ item.name }}/{{ item.version }}/{{ item.name }}.hpi
  with_items: jenkins['plugins']
  tags: ['jenkins', 'jenkins_plugins']

- name: safe-restart jenkins
  sudo: yes
  command: java -jar {{ jenkins['cli_dest'] }} -s http://localhost:{{ jenkins['port'] }} safe-restart
  tags: ['jenkins', 'jenkins_plugins']

- name: wait for jenkins to restart, it can take forever
  command: sleep 180
  tags: ['jenkins', 'jenkins_plugins']
